ames <- read.csv(file="C:/Users/matt/source/repos/ds710/lesson3/AmesHousing.csv")
attach(ames)
hist(SalePrice)
mx <- mean(SalePrice)
hist(SalePrice, xlab = "Price in Dollars", ylab = "Number of Houses", main = "My Awesome Histogram")
abline(v = mx, col = "?ed", lwd = 2)
medx <- median(SalePrice)
abline(v = medx, col = "blue", lwd = 3)
legend("topright", legend = c("Mean price", "Median price"), col=c("red","blue"),lwd=2,lty=(2,3))
